#!/usr/bin/env python3

# Imports
import os

# Script Body

## Variables

path = os.getcwd()
common_name = input("Insert a common name: ")
extension = input("Insert the extension of the files: ")

# What the script does

for i, f in enumerate(os.listdir(path)):
	index = '000'
	if i < 10:
		index = '00{}'.format(i)
	elif i >= 10 and i < 100:
		index = '0{}'.format(i)
	else:
		index = i
	f_new = '{0}-{1}.{2}'.format(common_name, index, extension)
	os.rename(f, f_new)
	print('{0}. {1} -> {2}'.format(i, f, f_new))
